USE [FamilyGroup]
GO

/****** Object:  Table [dbo].[E_Vehicle]    Script Date: 2015/8/19 ¤U¤È 05:06:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[E_Vehicle](
	[Veh_id] [int] IDENTITY(1,1) NOT NULL,
	[License] [varchar](15) NOT NULL,
	[Prop_id] [int] NULL,
	 CONSTRAINT [PK_E_Vehicle] PRIMARY KEY CLUSTERED 
	(
		[Veh_id] ASC
	)WITH (
		PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


