Use FamilyGroup
GO

--DELETE FROM [E_Company]
--GO
--DBCC CHECKIDENT ('[E_Company]',RESEED,0);
--GO

insert into [E_Company] (Name) values ('Eire');
insert into [E_Company] (Name) values ('Vinte');
insert into [E_Company] (Name) values ('Jatri');
insert into [E_Company] (Name) values ('Linkbuzz');
insert into [E_Company] (Name) values ('Yambee');
insert into [E_Company] (Name) values ('Gigabox');
insert into [E_Company] (Name) values ('Riffwire');
insert into [E_Company] (Name) values ('Tazzy');
insert into [E_Company] (Name) values ('Riffpedia');
insert into [E_Company] (Name) values ('Jaxbean');
insert into [E_Company] (Name) values ('Innojam');
insert into [E_Company] (Name) values ('Browsedrive');
insert into [E_Company] (Name) values ('Meejo');
insert into [E_Company] (Name) values ('Youopia');
insert into [E_Company] (Name) values ('Zazio');
insert into [E_Company] (Name) values ('Janyx');
insert into [E_Company] (Name) values ('Youspan');
insert into [E_Company] (Name) values ('Quimba');
insert into [E_Company] (Name) values ('Jabbertype');
insert into [E_Company] (Name) values ('Youspan');
insert into [E_Company] (Name) values ('Myworks');
insert into [E_Company] (Name) values ('Photolist');
insert into [E_Company] (Name) values ('Tagopia');
insert into [E_Company] (Name) values ('Skyba');
insert into [E_Company] (Name) values ('Rhyzio');
insert into [E_Company] (Name) values ('Tambee');
insert into [E_Company] (Name) values ('Divavu');
insert into [E_Company] (Name) values ('Linktype');
insert into [E_Company] (Name) values ('Zoonoodle');
insert into [E_Company] (Name) values ('Trudoo');
insert into [E_Company] (Name) values ('Rooxo');
insert into [E_Company] (Name) values ('Ntag');
insert into [E_Company] (Name) values ('Bubblemix');
insert into [E_Company] (Name) values ('Photolist');
insert into [E_Company] (Name) values ('Zava');
insert into [E_Company] (Name) values ('Jaxworks');
insert into [E_Company] (Name) values ('Jaxbean');
insert into [E_Company] (Name) values ('Thoughtbridge');
insert into [E_Company] (Name) values ('Jabbercube');
insert into [E_Company] (Name) values ('Jamia');
insert into [E_Company] (Name) values ('Mynte');
insert into [E_Company] (Name) values ('Jaxspan');
insert into [E_Company] (Name) values ('Edgetag');
insert into [E_Company] (Name) values ('Skiba');
insert into [E_Company] (Name) values ('Voonte');
insert into [E_Company] (Name) values ('Eire');
insert into [E_Company] (Name) values ('Thoughtsphere');
insert into [E_Company] (Name) values ('Abata');
insert into [E_Company] (Name) values ('Voonte');
insert into [E_Company] (Name) values ('Jaxbean');
INSERT INTO E_Company([Name]) VALUES('Ipsum Inc.');
INSERT INTO E_Company([Name]) VALUES('Lectus Institute');
INSERT INTO E_Company([Name]) VALUES('Sagittis Placerat Cras Institute');
INSERT INTO E_Company([Name]) VALUES('Posuere Ltd');
INSERT INTO E_Company([Name]) VALUES('Parturient Montes PC');
INSERT INTO E_Company([Name]) VALUES('Dis Parturient Montes Ltd');
INSERT INTO E_Company([Name]) VALUES('Vestibulum Ante Ipsum Limited');
INSERT INTO E_Company([Name]) VALUES('Risus Nulla Eget Associates');
INSERT INTO E_Company([Name]) VALUES('Gravida Molestie Arcu Inc.');
INSERT INTO E_Company([Name]) VALUES('Ornare Industries');
INSERT INTO E_Company([Name]) VALUES('Aliquam LLC');
INSERT INTO E_Company([Name]) VALUES('Vulputate Mauris Sagittis PC');
INSERT INTO E_Company([Name]) VALUES('Mauris Associates');
INSERT INTO E_Company([Name]) VALUES('Nullam Scelerisque Neque LLC');
INSERT INTO E_Company([Name]) VALUES('Arcu Eu Odio Corp.');
INSERT INTO E_Company([Name]) VALUES('Sollicitudin Corp.');
INSERT INTO E_Company([Name]) VALUES('Eu Eros Nam Corporation');
INSERT INTO E_Company([Name]) VALUES('Risus Morbi Ltd');
INSERT INTO E_Company([Name]) VALUES('Est PC');
INSERT INTO E_Company([Name]) VALUES('Libero Proin Mi Institute');
INSERT INTO E_Company([Name]) VALUES('Proin Eget Odio Foundation');
INSERT INTO E_Company([Name]) VALUES('Curabitur Inc.');
INSERT INTO E_Company([Name]) VALUES('Odio Consulting');
INSERT INTO E_Company([Name]) VALUES('Etiam Inc.');
INSERT INTO E_Company([Name]) VALUES('Nulla Inc.');
INSERT INTO E_Company([Name]) VALUES('Velit Cras PC');
INSERT INTO E_Company([Name]) VALUES('Sit Institute');
INSERT INTO E_Company([Name]) VALUES('Non Arcu Company');
INSERT INTO E_Company([Name]) VALUES('Est Mollis Non Corporation');
INSERT INTO E_Company([Name]) VALUES('Vel Limited');
INSERT INTO E_Company([Name]) VALUES('Morbi Accumsan Laoreet Consulting');
INSERT INTO E_Company([Name]) VALUES('Feugiat Lorem Foundation');
INSERT INTO E_Company([Name]) VALUES('Ac Mattis Consulting');
INSERT INTO E_Company([Name]) VALUES('Inceptos Hymenaeos Institute');
INSERT INTO E_Company([Name]) VALUES('Egestas A Corporation');
INSERT INTO E_Company([Name]) VALUES('Aliquet LLC');
INSERT INTO E_Company([Name]) VALUES('Purus Sapien Gravida Corp.');
INSERT INTO E_Company([Name]) VALUES('Erat Etiam Vestibulum Corp.');
INSERT INTO E_Company([Name]) VALUES('Lacus Pede Sagittis Corp.');
INSERT INTO E_Company([Name]) VALUES('Curabitur Massa Limited');
INSERT INTO E_Company([Name]) VALUES('Nibh Lacinia PC');
INSERT INTO E_Company([Name]) VALUES('Erat Sed Nunc LLC');
INSERT INTO E_Company([Name]) VALUES('Velit Justo Nec Institute');
INSERT INTO E_Company([Name]) VALUES('Lacinia Limited');
INSERT INTO E_Company([Name]) VALUES('In Ltd');
INSERT INTO E_Company([Name]) VALUES('Dolor Industries');
INSERT INTO E_Company([Name]) VALUES('Amet Corp.');
INSERT INTO E_Company([Name]) VALUES('Vitae Odio LLC');
INSERT INTO E_Company([Name]) VALUES('Morbi Tristique LLP');
INSERT INTO E_Company([Name]) VALUES('Pellentesque Incorporated');
INSERT INTO E_Company([Name]) VALUES('Mus Donec Incorporated');
INSERT INTO E_Company([Name]) VALUES('Condimentum Donec Company');
INSERT INTO E_Company([Name]) VALUES('Duis Mi Enim Corp.');
INSERT INTO E_Company([Name]) VALUES('Arcu Nunc Limited');
INSERT INTO E_Company([Name]) VALUES('Est LLP');
INSERT INTO E_Company([Name]) VALUES('Consequat Limited');
INSERT INTO E_Company([Name]) VALUES('Erat Company');
INSERT INTO E_Company([Name]) VALUES('Maecenas Malesuada Incorporated');
INSERT INTO E_Company([Name]) VALUES('Morbi Vehicula Pellentesque LLP');
INSERT INTO E_Company([Name]) VALUES('Lorem Auctor Ltd');
INSERT INTO E_Company([Name]) VALUES('Lobortis Augue Ltd');
INSERT INTO E_Company([Name]) VALUES('Vulputate Velit Eu Ltd');
INSERT INTO E_Company([Name]) VALUES('Lacus PC');
INSERT INTO E_Company([Name]) VALUES('Montes Nascetur Ridiculus LLC');
INSERT INTO E_Company([Name]) VALUES('Cras Industries');
INSERT INTO E_Company([Name]) VALUES('Metus Vivamus Euismod Consulting');
INSERT INTO E_Company([Name]) VALUES('Pede LLP');
INSERT INTO E_Company([Name]) VALUES('Nibh Quisque Ltd');
INSERT INTO E_Company([Name]) VALUES('Felis Nulla Tempor Company');
INSERT INTO E_Company([Name]) VALUES('Posuere Enim Nisl LLP');
INSERT INTO E_Company([Name]) VALUES('Eget Massa LLC');
INSERT INTO E_Company([Name]) VALUES('Dictum Proin Company');
INSERT INTO E_Company([Name]) VALUES('Scelerisque Associates');
INSERT INTO E_Company([Name]) VALUES('Elit Consulting');
INSERT INTO E_Company([Name]) VALUES('Non Sapien Industries');
INSERT INTO E_Company([Name]) VALUES('Sed Neque Institute');
INSERT INTO E_Company([Name]) VALUES('Dignissim Tempor Arcu Corporation');
INSERT INTO E_Company([Name]) VALUES('Lobortis PC');
INSERT INTO E_Company([Name]) VALUES('Magnis Dis Parturient Foundation');
INSERT INTO E_Company([Name]) VALUES('Nostra Inc.');
INSERT INTO E_Company([Name]) VALUES('Imperdiet Associates');
INSERT INTO E_Company([Name]) VALUES('Blandit Limited');
INSERT INTO E_Company([Name]) VALUES('Elit A Institute');
INSERT INTO E_Company([Name]) VALUES('Semper Pretium Associates');
INSERT INTO E_Company([Name]) VALUES('Amet Ante Vivamus Foundation');
INSERT INTO E_Company([Name]) VALUES('Nulla Facilisi Incorporated');
INSERT INTO E_Company([Name]) VALUES('Scelerisque Neque Nullam Inc.');
INSERT INTO E_Company([Name]) VALUES('Vestibulum Mauris Magna Ltd');
INSERT INTO E_Company([Name]) VALUES('In At Pede Industries');
INSERT INTO E_Company([Name]) VALUES('Donec Vitae Erat Industries');
INSERT INTO E_Company([Name]) VALUES('In Industries');
INSERT INTO E_Company([Name]) VALUES('Orci Ltd');
INSERT INTO E_Company([Name]) VALUES('Montes Nascetur Ridiculus PC');
INSERT INTO E_Company([Name]) VALUES('Diam PC');
INSERT INTO E_Company([Name]) VALUES('Adipiscing Enim Mi Foundation');
INSERT INTO E_Company([Name]) VALUES('Ac Metus PC');
INSERT INTO E_Company([Name]) VALUES('Suscipit Nonummy Limited');
INSERT INTO E_Company([Name]) VALUES('Quis Company');
INSERT INTO E_Company([Name]) VALUES('Nibh Quisque Foundation');
INSERT INTO E_Company([Name]) VALUES('Pede Malesuada Inc.');