USE FamilyGroup
GO


--DELETE FROM E_Place
--DBCC CHECKIDENT ('[E_Place]',RESEED,0);
--GO

--ALTER TABLE [E_Place]
--ALTER COLUMN [Country] nvarchar(50) not null

INSERT INTO E_Place([City],[Country]) VALUES('Sint-Martens-Bodegem','Tuvalu');
INSERT INTO E_Place([City],[Country]) VALUES('Henley-on-Thames','Norway');
INSERT INTO E_Place([City],[Country]) VALUES('Elgin','Bahamas');
INSERT INTO E_Place([City],[Country]) VALUES('Eckville','Burundi');
INSERT INTO E_Place([City],[Country]) VALUES('Itabuna','Benin');
INSERT INTO E_Place([City],[Country]) VALUES('Quinte West','Bosnia and Herzegovina');
INSERT INTO E_Place([City],[Country]) VALUES('Huntsville','Colombia');
INSERT INTO E_Place([City],[Country]) VALUES('Srinagar','Malawi');
INSERT INTO E_Place([City],[Country]) VALUES('Raj Nandgaon','Cook Islands');
INSERT INTO E_Place([City],[Country]) VALUES('Assiniboia','Tajikistan');
INSERT INTO E_Place([City],[Country]) VALUES('Lugo','Kenya');
INSERT INTO E_Place([City],[Country]) VALUES('Bristol','Papua New Guinea');
INSERT INTO E_Place([City],[Country]) VALUES('Collines-de-l''Outaouais','Malaysia');
INSERT INTO E_Place([City],[Country]) VALUES('Kisi','Togo');
INSERT INTO E_Place([City],[Country]) VALUES('Reus','Curaçao');
INSERT INTO E_Place([City],[Country]) VALUES('Villamassargia','Gibraltar');
INSERT INTO E_Place([City],[Country]) VALUES('Ludhiana','Saint Lucia');
INSERT INTO E_Place([City],[Country]) VALUES('Alloa','Mauritius');
INSERT INTO E_Place([City],[Country]) VALUES('Feldkirchen in Kärnten','Reunion');
INSERT INTO E_Place([City],[Country]) VALUES('Sossano','Uruguay');
INSERT INTO E_Place([City],[Country]) VALUES('Tuktoyaktuk','Saint Vincent and The Grenadines');
INSERT INTO E_Place([City],[Country]) VALUES('Virelles','Fiji');
INSERT INTO E_Place([City],[Country]) VALUES('Granada','Bhutan');
INSERT INTO E_Place([City],[Country]) VALUES('Hattiesburg','Seychelles');
INSERT INTO E_Place([City],[Country]) VALUES('Erli','Sao Tome and Principe');
INSERT INTO E_Place([City],[Country]) VALUES('Annone di Brianza','Niue');
INSERT INTO E_Place([City],[Country]) VALUES('Smoky Lake','Northern Mariana Islands');
INSERT INTO E_Place([City],[Country]) VALUES('Trier','Armenia');
INSERT INTO E_Place([City],[Country]) VALUES('Pointe-du-Lac','Panama');
INSERT INTO E_Place([City],[Country]) VALUES('Burnaby','Bhutan');
INSERT INTO E_Place([City],[Country]) VALUES('Villers-le-Peuplier','Cuba');
INSERT INTO E_Place([City],[Country]) VALUES('Torella del Sannio','Peru');
INSERT INTO E_Place([City],[Country]) VALUES('Merseburg','Sint Maarten');
INSERT INTO E_Place([City],[Country]) VALUES('Gönen','Jersey');
INSERT INTO E_Place([City],[Country]) VALUES('Fort St. John','Bonaire, Sint Eustatius and Saba');
INSERT INTO E_Place([City],[Country]) VALUES('Bruderheim','United States Minor Outlying Islands');
INSERT INTO E_Place([City],[Country]) VALUES('Vandoeuvre-lès-Nancy','Colombia');
INSERT INTO E_Place([City],[Country]) VALUES('Huissen','Korea, North');
INSERT INTO E_Place([City],[Country]) VALUES('Burns Lake','Israel');
INSERT INTO E_Place([City],[Country]) VALUES('Linz','Zimbabwe');
INSERT INTO E_Place([City],[Country]) VALUES('Baricella','Puerto Rico');
INSERT INTO E_Place([City],[Country]) VALUES('St. Austell','Suriname');
INSERT INTO E_Place([City],[Country]) VALUES('Ingooigem','Nigeria');
INSERT INTO E_Place([City],[Country]) VALUES('Spittal an der Drau','Albania');
INSERT INTO E_Place([City],[Country]) VALUES('Edmundston','Belize');
INSERT INTO E_Place([City],[Country]) VALUES('Orosei','Afghanistan');
INSERT INTO E_Place([City],[Country]) VALUES('Feira de Santana','Papua New Guinea');
INSERT INTO E_Place([City],[Country]) VALUES('Palagano','Barbados');
INSERT INTO E_Place([City],[Country]) VALUES('Wörgl','Indonesia');
INSERT INTO E_Place([City],[Country]) VALUES('Potenza','French Guiana');
INSERT INTO E_Place([City],[Country]) VALUES('Cassano Spinola','Chile');
INSERT INTO E_Place([City],[Country]) VALUES('Criciúma','Christmas Island');
INSERT INTO E_Place([City],[Country]) VALUES('Biggleswade','Belize');
INSERT INTO E_Place([City],[Country]) VALUES('Concepción','Nigeria');
INSERT INTO E_Place([City],[Country]) VALUES('Comblain-Fairon','Cuba');
INSERT INTO E_Place([City],[Country]) VALUES('Pittsburgh','Senegal');
INSERT INTO E_Place([City],[Country]) VALUES('Leers-et-Fosteau','Moldova');
INSERT INTO E_Place([City],[Country]) VALUES('Saint-Laurent','Norfolk Island');
INSERT INTO E_Place([City],[Country]) VALUES('Ellon','Australia');
INSERT INTO E_Place([City],[Country]) VALUES('Kingston','Nauru');
INSERT INTO E_Place([City],[Country]) VALUES('Beaumont','Puerto Rico');
INSERT INTO E_Place([City],[Country]) VALUES('Lelystad','Ecuador');
INSERT INTO E_Place([City],[Country]) VALUES('Joliet','Belgium');
INSERT INTO E_Place([City],[Country]) VALUES('Worcester','Iran');
INSERT INTO E_Place([City],[Country]) VALUES('Nivelles','Russian Federation');
INSERT INTO E_Place([City],[Country]) VALUES('Irricana','Jersey');
INSERT INTO E_Place([City],[Country]) VALUES('Banff','Virgin Islands, United States');
INSERT INTO E_Place([City],[Country]) VALUES('Colomiers','Qatar');
INSERT INTO E_Place([City],[Country]) VALUES('Haridwar','Cook Islands');
INSERT INTO E_Place([City],[Country]) VALUES('Cassaro','Eritrea');
INSERT INTO E_Place([City],[Country]) VALUES('Kapolei','Brazil');
INSERT INTO E_Place([City],[Country]) VALUES('Isola di Capo Rizzuto','Aruba');
INSERT INTO E_Place([City],[Country]) VALUES('Sfruz','Malta');
INSERT INTO E_Place([City],[Country]) VALUES('Henderson','Cyprus');
INSERT INTO E_Place([City],[Country]) VALUES('Asse','Cayman Islands');
INSERT INTO E_Place([City],[Country]) VALUES('Gelsenkirchen','Trinidad and Tobago');
INSERT INTO E_Place([City],[Country]) VALUES('Lanark','Côte D''Ivoire (Ivory Coast)');
INSERT INTO E_Place([City],[Country]) VALUES('Aurora','Bahrain');
INSERT INTO E_Place([City],[Country]) VALUES('LaSalle','Norway');
INSERT INTO E_Place([City],[Country]) VALUES('Caldarola','Nepal');
INSERT INTO E_Place([City],[Country]) VALUES('Tramutola','Viet Nam');
INSERT INTO E_Place([City],[Country]) VALUES('Roermond','Colombia');
INSERT INTO E_Place([City],[Country]) VALUES('Surbo','Bahamas');
INSERT INTO E_Place([City],[Country]) VALUES('Vance','Falkland Islands');
INSERT INTO E_Place([City],[Country]) VALUES('Rignano Garganico','Côte D''Ivoire (Ivory Coast)');
INSERT INTO E_Place([City],[Country]) VALUES('Montreal','Morocco');
INSERT INTO E_Place([City],[Country]) VALUES('Panipat','Serbia');
INSERT INTO E_Place([City],[Country]) VALUES('Rangiora','Russian Federation');
INSERT INTO E_Place([City],[Country]) VALUES('Sogliano Cavour','Svalbard and Jan Mayen Islands');
INSERT INTO E_Place([City],[Country]) VALUES('Nanded','Laos');
INSERT INTO E_Place([City],[Country]) VALUES('Kearny','Reunion');
INSERT INTO E_Place([City],[Country]) VALUES('Leers-et-Fosteau','Cyprus');
INSERT INTO E_Place([City],[Country]) VALUES('Columbus','Bahrain');
INSERT INTO E_Place([City],[Country]) VALUES('Eisleben','Latvia');
INSERT INTO E_Place([City],[Country]) VALUES('Leighton Buzzard','Barbados');
INSERT INTO E_Place([City],[Country]) VALUES('Acquafredda','Tuvalu');
INSERT INTO E_Place([City],[Country]) VALUES('Velden am Wörther See','Northern Mariana Islands');
INSERT INTO E_Place([City],[Country]) VALUES('Montbéliard','Peru');
INSERT INTO E_Place([City],[Country]) VALUES('Seattle','Myanmar');
insert into E_Place (City, Country) values ('Gouyan', 'China');
insert into E_Place (City, Country) values ('Sasaguri', 'Japan');
insert into E_Place (City, Country) values ('Moulay Yacoub', 'Morocco');
insert into E_Place (City, Country) values ('Renhe', 'China');
insert into E_Place (City, Country) values ('Cipanggung', 'Indonesia');
insert into E_Place (City, Country) values ('Tambo', 'Philippines');
insert into E_Place (City, Country) values ('Legrada', 'Philippines');
insert into E_Place (City, Country) values ('Adare', 'Ireland');
insert into E_Place (City, Country) values ('Concepción de La Vega', 'Dominican Republic');
insert into E_Place (City, Country) values ('Čačak', 'Serbia');
insert into E_Place (City, Country) values ('Colorado Springs', 'United States');
insert into E_Place (City, Country) values ('Sīlat al Ḩārithīyah', 'Palestinian Territory');
insert into E_Place (City, Country) values ('Saint-Leu-la-Forêt', 'France');
insert into E_Place (City, Country) values ('Lumbayan', 'Philippines');
insert into E_Place (City, Country) values ('Bangunsari', 'Indonesia');
insert into E_Place (City, Country) values ('Fenghuangshan', 'China');
insert into E_Place (City, Country) values ('Mirabel', 'Canada');
insert into E_Place (City, Country) values ('Budapest', 'Hungary');
insert into E_Place (City, Country) values ('Dauphin', 'Canada');
insert into E_Place (City, Country) values ('Shuntian', 'China');
insert into E_Place (City, Country) values ('Gazli', 'Uzbekistan');
insert into E_Place (City, Country) values ('Daba', 'China');
insert into E_Place (City, Country) values ('Krajan', 'Indonesia');
insert into E_Place (City, Country) values ('Jicomé', 'Dominican Republic');
insert into E_Place (City, Country) values ('Dacheng', 'China');
insert into E_Place (City, Country) values ('Berlin', 'Germany');
insert into E_Place (City, Country) values ('Panaytayon', 'Philippines');
insert into E_Place (City, Country) values ('Bressuire', 'France');
insert into E_Place (City, Country) values ('Racławice', 'Poland');
insert into E_Place (City, Country) values ('Videira', 'Brazil');
insert into E_Place (City, Country) values ('Santa Marta', 'Colombia');
insert into E_Place (City, Country) values ('Lloque', 'Peru');
insert into E_Place (City, Country) values ('Langford', 'Canada');
insert into E_Place (City, Country) values ('Primorka', 'Russia');
insert into E_Place (City, Country) values ('Póvoa', 'Portugal');
insert into E_Place (City, Country) values ('Angoulême', 'France');
insert into E_Place (City, Country) values ('Voronezh', 'Russia');
insert into E_Place (City, Country) values ('Shahezi', 'China');
insert into E_Place (City, Country) values ('Bualu', 'Indonesia');
insert into E_Place (City, Country) values ('Karangbenda', 'Indonesia');
insert into E_Place (City, Country) values ('Palestina', 'Colombia');
insert into E_Place (City, Country) values ('Ciladaeun', 'Indonesia');
insert into E_Place (City, Country) values ('Zhengguo', 'China');
insert into E_Place (City, Country) values ('Sukhirin', 'Thailand');
insert into E_Place (City, Country) values ('Athlone', 'Ireland');
insert into E_Place (City, Country) values ('Kota Kinabalu', 'Malaysia');
insert into E_Place (City, Country) values ('Envigado', 'Colombia');
insert into E_Place (City, Country) values ('Yuqunweng', 'China');
insert into E_Place (City, Country) values ('Sheshan', 'China');
insert into E_Place (City, Country) values ('Tālīn', 'Syria');
insert into E_Place (City, Country) values ('Şurmān', 'Libya');
insert into E_Place (City, Country) values ('Oslo', 'Norway');
insert into E_Place (City, Country) values ('Malawa', 'Philippines');
insert into E_Place (City, Country) values ('Dal’nerechensk', 'Russia');
insert into E_Place (City, Country) values ('Shiroishi', 'Japan');
insert into E_Place (City, Country) values ('Drammen', 'Norway');
insert into E_Place (City, Country) values ('Bukal Sur', 'Philippines');
insert into E_Place (City, Country) values ('Bokino', 'Russia');
insert into E_Place (City, Country) values ('Jiushe', 'China');
insert into E_Place (City, Country) values ('Rio Brilhante', 'Brazil');
insert into E_Place (City, Country) values ('Kawengan', 'Indonesia');
insert into E_Place (City, Country) values ('Kambing', 'Philippines');
insert into E_Place (City, Country) values ('Hengxianhe', 'China');
insert into E_Place (City, Country) values ('Takahagi', 'Japan');
insert into E_Place (City, Country) values ('Stylída', 'Greece');
insert into E_Place (City, Country) values ('Karangampel', 'Indonesia');
insert into E_Place (City, Country) values ('Sobienie Jeziory', 'Poland');
insert into E_Place (City, Country) values ('Kertasari', 'Indonesia');
insert into E_Place (City, Country) values ('Tejar', 'Costa Rica');
insert into E_Place (City, Country) values ('Bang Racham', 'Thailand');
insert into E_Place (City, Country) values ('Sukarama', 'Indonesia');
insert into E_Place (City, Country) values ('Buzdyak', 'Russia');
insert into E_Place (City, Country) values ('Bang Rakam', 'Thailand');
insert into E_Place (City, Country) values ('Caridad', 'Philippines');
insert into E_Place (City, Country) values ('Szczecin', 'Poland');
insert into E_Place (City, Country) values ('Shantoudian', 'China');
insert into E_Place (City, Country) values ('Jiaokui', 'China');
insert into E_Place (City, Country) values ('Duzhou', 'China');
insert into E_Place (City, Country) values ('Takum', 'Nigeria');
insert into E_Place (City, Country) values ('Sinisian', 'Philippines');
insert into E_Place (City, Country) values ('Longtang', 'China');
insert into E_Place (City, Country) values ('Penja', 'Cameroon');
insert into E_Place (City, Country) values ('Mamfe', 'Cameroon');
insert into E_Place (City, Country) values ('Benhao', 'China');
insert into E_Place (City, Country) values ('Al Ḩumaydāt', 'Yemen');
insert into E_Place (City, Country) values ('Binjai', 'Indonesia');
insert into E_Place (City, Country) values ('Kuala Lumpur', 'Malaysia');
insert into E_Place (City, Country) values ('Rio Formoso', 'Brazil');
insert into E_Place (City, Country) values ('Podgornaya', 'Russia');
insert into E_Place (City, Country) values ('Shreveport', 'United States');
insert into E_Place (City, Country) values ('Walce', 'Poland');
insert into E_Place (City, Country) values ('Cacocum', 'Cuba');
insert into E_Place (City, Country) values ('Stutterheim', 'South Africa');
insert into E_Place (City, Country) values ('Sanyi', 'China');
insert into E_Place (City, Country) values ('Roissy Charles-de-Gaulle', 'France');
insert into E_Place (City, Country) values ('Sergiyev Posad', 'Russia');
insert into E_Place (City, Country) values ('Dajabón', 'Dominican Republic');
insert into E_Place (City, Country) values ('Famaillá', 'Argentina');
insert into E_Place (City, Country) values ('Jorong', 'Indonesia');
insert into E_Place (City, Country) values ('Bagneux', 'France');
insert into E_Place (City, Country) values ('Zwettl', 'Austria');
insert into E_Place (City, Country) values ('Gyangqai', 'China');
insert into E_Place (City, Country) values ('Kembangkerang Lauk Timur', 'Indonesia');
insert into E_Place (City, Country) values ('Guernica', 'Argentina');
insert into E_Place (City, Country) values ('Roma', 'Italy');
insert into E_Place (City, Country) values ('Shanggu', 'China');
insert into E_Place (City, Country) values ('Suru', 'Indonesia');
insert into E_Place (City, Country) values ('Indianapolis', 'United States');
insert into E_Place (City, Country) values ('San José de Barlovento', 'Venezuela');
insert into E_Place (City, Country) values ('Sabandia', 'Peru');
insert into E_Place (City, Country) values ('Mawa', 'Indonesia');
insert into E_Place (City, Country) values ('Fort Worth', 'United States');
insert into E_Place (City, Country) values ('Mashiko', 'Japan');
insert into E_Place (City, Country) values ('Yuyang', 'China');
insert into E_Place (City, Country) values ('Don Matías', 'Colombia');
insert into E_Place (City, Country) values ('Bela Vista', 'Brazil');
insert into E_Place (City, Country) values ('Zhoushizhuang', 'China');
insert into E_Place (City, Country) values ('Néa Róda', 'Greece');
insert into E_Place (City, Country) values ('Arcos de Valdevez', 'Portugal');
insert into E_Place (City, Country) values ('Tosno', 'Russia');
insert into E_Place (City, Country) values ('Čoka', 'Serbia');
insert into E_Place (City, Country) values ('Tefé', 'Brazil');
insert into E_Place (City, Country) values ('Lubbock', 'United States');
insert into E_Place (City, Country) values ('Song', 'Thailand');
insert into E_Place (City, Country) values ('Kyrylivka', 'Ukraine');
insert into E_Place (City, Country) values ('Gose', 'Japan');
insert into E_Place (City, Country) values ('Gontar', 'Indonesia');
insert into E_Place (City, Country) values ('Umag', 'Croatia');
insert into E_Place (City, Country) values ('Wuluo', 'China');
insert into E_Place (City, Country) values ('Turku', 'Finland');
insert into E_Place (City, Country) values ('Bom Sucesso', 'Portugal');
insert into E_Place (City, Country) values ('Ludbreg', 'Croatia');
insert into E_Place (City, Country) values ('Volgograd', 'Russia');
insert into E_Place (City, Country) values ('København', 'Denmark');
insert into E_Place (City, Country) values ('Alilem', 'Philippines');
insert into E_Place (City, Country) values ('Esmoriz', 'Portugal');
insert into E_Place (City, Country) values ('Calle Blancos', 'Costa Rica');
insert into E_Place (City, Country) values ('Tallaght', 'Ireland');
insert into E_Place (City, Country) values ('Tsyurupyns’k', 'Ukraine');
insert into E_Place (City, Country) values ('Canggang', 'China');
insert into E_Place (City, Country) values ('Cipunglu', 'Indonesia');
insert into E_Place (City, Country) values ('Afareaitu', 'French Polynesia');
insert into E_Place (City, Country) values ('Mokil', 'Micronesia');
insert into E_Place (City, Country) values ('Caujul', 'Peru');
insert into E_Place (City, Country) values ('Kisesa', 'Tanzania');
insert into E_Place (City, Country) values ('Uruzgān', 'Afghanistan');
insert into E_Place (City, Country) values ('Abut', 'Philippines');
insert into E_Place (City, Country) values ('Stoszowice', 'Poland');
insert into E_Place (City, Country) values ('Kineshma', 'Russia');
insert into E_Place (City, Country) values ('Margorejo', 'Indonesia');
insert into E_Place (City, Country) values ('Breda', 'Netherlands');
insert into E_Place (City, Country) values ('Gradići', 'Croatia');
insert into E_Place (City, Country) values ('Oslo', 'Norway');
insert into E_Place (City, Country) values ('San Antonio Oeste', 'Argentina');
insert into E_Place (City, Country) values ('Orlando', 'United States');
insert into E_Place (City, Country) values ('Paris 02', 'France');
insert into E_Place (City, Country) values ('Saint-Jean-de-Védas', 'France');
insert into E_Place (City, Country) values ('Remolino', 'Colombia');
insert into E_Place (City, Country) values ('Krajan Kinanti', 'Indonesia');
insert into E_Place (City, Country) values ('Belyye Stolby', 'Russia');
insert into E_Place (City, Country) values ('Ośno Lubuskie', 'Poland');
insert into E_Place (City, Country) values ('Zhifudao', 'China');
insert into E_Place (City, Country) values ('Marolambo', 'Madagascar');
insert into E_Place (City, Country) values ('Batticaloa', 'Sri Lanka');
insert into E_Place (City, Country) values ('Caluire-et-Cuire', 'France');
insert into E_Place (City, Country) values ('Grati Satu', 'Indonesia');
insert into E_Place (City, Country) values ('Bedayutalang', 'Indonesia');
insert into E_Place (City, Country) values ('Haoguantun', 'China');
insert into E_Place (City, Country) values ('Maguilling', 'Philippines');
insert into E_Place (City, Country) values ('Battaramulla South', 'Sri Lanka');
insert into E_Place (City, Country) values ('Gujiadian', 'China');
insert into E_Place (City, Country) values ('Washington', 'United States');
insert into E_Place (City, Country) values ('Liuxiang', 'China');
insert into E_Place (City, Country) values ('Shlissel’burg', 'Russia');
insert into E_Place (City, Country) values ('Lubrza', 'Poland');
insert into E_Place (City, Country) values ('Igarapava', 'Brazil');
insert into E_Place (City, Country) values ('Montonggamang', 'Indonesia');
insert into E_Place (City, Country) values ('Mouquim', 'Portugal');
insert into E_Place (City, Country) values ('Kirkton', 'United Kingdom');
insert into E_Place (City, Country) values ('Châu Thành', 'Vietnam');
insert into E_Place (City, Country) values ('Yinping', 'China');
insert into E_Place (City, Country) values ('Kota Kinabalu', 'Malaysia');
insert into E_Place (City, Country) values ('Łodygowice', 'Poland');
insert into E_Place (City, Country) values ('Muzidian', 'China');
insert into E_Place (City, Country) values ('Dąbrowa', 'Poland');
insert into E_Place (City, Country) values ('Krajan Dua Patempuran', 'Indonesia');
insert into E_Place (City, Country) values ('Pumwani', 'Kenya');
insert into E_Place (City, Country) values ('Błaszki', 'Poland');
insert into E_Place (City, Country) values ('Mutangyuan', 'China');
insert into E_Place (City, Country) values ('Krasni Okny', 'Ukraine');
insert into E_Place (City, Country) values ('Yumbel', 'Chile');
insert into E_Place (City, Country) values ('Asenovgrad', 'Bulgaria');
insert into E_Place (City, Country) values ('Huangtan', 'China');
insert into E_Place (City, Country) values ('Tampakan', 'Philippines');
insert into E_Place (City, Country) values ('Bauan', 'Philippines');
insert into E_Place (City, Country) values ('Souto de Cima', 'Portugal');
insert into E_Place (City, Country) values ('Log pri Brezovici', 'Slovenia');
insert into E_Place (City, Country) values ('Tinaquillo', 'Venezuela');
insert into E_Place (City, Country) values ('Eskilstuna', 'Sweden');
insert into E_Place (City, Country) values ('Paringin', 'Indonesia');
insert into E_Place (City, Country) values ('Ulricehamn', 'Sweden');
insert into E_Place (City, Country) values ('Águas de Lindóia', 'Brazil');
insert into E_Place (City, Country) values ('Kesugihan', 'Indonesia');
insert into E_Place (City, Country) values ('Wailolung', 'Indonesia');
insert into E_Place (City, Country) values ('Dungarvan', 'Ireland');
insert into E_Place (City, Country) values ('Pingtan', 'China');
insert into E_Place (City, Country) values ('Liozon', 'Philippines');
insert into E_Place (City, Country) values ('Jiangchang', 'China');
insert into E_Place (City, Country) values ('Ciroyom', 'Indonesia');
insert into E_Place (City, Country) values ('Paterson', 'United States');
insert into E_Place (City, Country) values ('Bjärred', 'Sweden');
insert into E_Place (City, Country) values ('Fengle', 'China');
insert into E_Place (City, Country) values ('Mūdīyah', 'Yemen');
insert into E_Place (City, Country) values ('Ōmura', 'Japan');
insert into E_Place (City, Country) values ('Rueil-Malmaison', 'France');
insert into E_Place (City, Country) values ('Shiyuan', 'China');
insert into E_Place (City, Country) values ('Panalo-on', 'Philippines');
insert into E_Place (City, Country) values ('Ostrowite', 'Poland');
insert into E_Place (City, Country) values ('Baunu-Timbangan', 'Philippines');
insert into E_Place (City, Country) values ('Barraute', 'Canada');
insert into E_Place (City, Country) values ('Bailan', 'Philippines');
insert into E_Place (City, Country) values ('Okuta', 'Nigeria');
insert into E_Place (City, Country) values ('Tongzha', 'China');
insert into E_Place (City, Country) values ('Clodomira', 'Argentina');
insert into E_Place (City, Country) values ('Vulcan', 'Canada');
insert into E_Place (City, Country) values ('Kandhkot', 'Pakistan');
insert into E_Place (City, Country) values ('Bichura', 'Russia');
insert into E_Place (City, Country) values ('Göteborg', 'Sweden');
insert into E_Place (City, Country) values ('Buta', 'Democratic Republic of the Congo');
insert into E_Place (City, Country) values ('Thulamahashi', 'South Africa');
insert into E_Place (City, Country) values ('Moerewa', 'New Zealand');
insert into E_Place (City, Country) values ('Kutao', 'China');
insert into E_Place (City, Country) values ('Muff', 'Ireland');
insert into E_Place (City, Country) values ('Poroj', 'Macedonia');
insert into E_Place (City, Country) values ('Jiangkouxu', 'China');
insert into E_Place (City, Country) values ('Banaybanay', 'Philippines');
insert into E_Place (City, Country) values ('Yangqing', 'China');
insert into E_Place (City, Country) values ('Sławoborze', 'Poland');
insert into E_Place (City, Country) values ('Créteil', 'France');
insert into E_Place (City, Country) values ('Jatibonico', 'Cuba');
insert into E_Place (City, Country) values ('Orahovac', 'Kosovo');
insert into E_Place (City, Country) values ('Yanmen', 'China');
insert into E_Place (City, Country) values ('Tumu’ertai', 'China');
insert into E_Place (City, Country) values ('Palmas de Monte Alto', 'Brazil');
insert into E_Place (City, Country) values ('Timeng', 'China');
insert into E_Place (City, Country) values ('Guangang', 'China');
insert into E_Place (City, Country) values ('Cergy-Pontoise', 'France');
insert into E_Place (City, Country) values ('Estombar', 'Portugal');
insert into E_Place (City, Country) values ('Beijie', 'China');
insert into E_Place (City, Country) values ('Dulangan', 'Philippines');
insert into E_Place (City, Country) values ('Jijiazhuang', 'China');
insert into E_Place (City, Country) values ('Kuta', 'Nigeria');
insert into E_Place (City, Country) values ('Rognedino', 'Russia');
insert into E_Place (City, Country) values ('Macaíba', 'Brazil');
insert into E_Place (City, Country) values ('Pilar do Sul', 'Brazil');
insert into E_Place (City, Country) values ('Lappi', 'Finland');
insert into E_Place (City, Country) values ('Rubizhne', 'Ukraine');
insert into E_Place (City, Country) values ('Xinning', 'China');
insert into E_Place (City, Country) values ('Sandakan', 'Malaysia');
insert into E_Place (City, Country) values ('Emiliano Zapata', 'Mexico');
insert into E_Place (City, Country) values ('Semamung', 'Indonesia');
insert into E_Place (City, Country) values ('Clearwater', 'United States');
insert into E_Place (City, Country) values ('Feilaixia', 'China');
insert into E_Place (City, Country) values ('Omoku', 'Nigeria');
insert into E_Place (City, Country) values ('Veliki Preslav', 'Bulgaria');
insert into E_Place (City, Country) values ('Amalfi', 'Colombia');
insert into E_Place (City, Country) values ('Biljača', 'Serbia');
insert into E_Place (City, Country) values ('Babak', 'Philippines');
insert into E_Place (City, Country) values ('Qarāwul', 'Afghanistan');
insert into E_Place (City, Country) values ('Xinshichang', 'China');
insert into E_Place (City, Country) values ('Plaisir', 'France');
insert into E_Place (City, Country) values ('Lyon', 'France');
insert into E_Place (City, Country) values ('Ystad', 'Sweden');
insert into E_Place (City, Country) values ('Rybinsk', 'Russia');
insert into E_Place (City, Country) values ('Storozhevaya', 'Russia');
insert into E_Place (City, Country) values ('Tønsberg', 'Norway');
insert into E_Place (City, Country) values ('San Juan', 'Puerto Rico');
insert into E_Place (City, Country) values ('Hachiōji', 'Japan');
insert into E_Place (City, Country) values ('Upernavik', 'Greenland');
insert into E_Place (City, Country) values ('Yamen', 'China');
insert into E_Place (City, Country) values ('Červené Pečky', 'Czech Republic');
insert into E_Place (City, Country) values ('Saint-Denis', 'Reunion');
insert into E_Place (City, Country) values ('Rochefort', 'France');
insert into E_Place (City, Country) values ('Kalodzishchy', 'Belarus');
insert into E_Place (City, Country) values ('Shangtuhai', 'China');
insert into E_Place (City, Country) values ('Kaom', 'Indonesia');
insert into E_Place (City, Country) values ('El Quebrachal', 'Argentina');
insert into E_Place (City, Country) values ('Sumuragung', 'Indonesia');
insert into E_Place (City, Country) values ('Sighnaghi', 'Georgia');
insert into E_Place (City, Country) values ('Amboise', 'France');
insert into E_Place (City, Country) values ('Chengdong', 'China');
insert into E_Place (City, Country) values ('San Carlos de Bariloche', 'Argentina');
insert into E_Place (City, Country) values ('Lengshuijing', 'China');
insert into E_Place (City, Country) values ('Bodø', 'Norway');
insert into E_Place (City, Country) values ('Cluny', 'Mauritius');
insert into E_Place (City, Country) values ('Palaiochóri', 'Greece');
insert into E_Place (City, Country) values ('Yafran', 'Libya');
insert into E_Place (City, Country) values ('Bakuriani', 'Georgia');
insert into E_Place (City, Country) values ('Asikkala', 'Finland');
insert into E_Place (City, Country) values ('Huaqiao', 'China');
insert into E_Place (City, Country) values ('Chalaco', 'Peru');
insert into E_Place (City, Country) values ('Parumaan', 'Indonesia');
insert into E_Place (City, Country) values ('Xiaotang', 'China');
insert into E_Place (City, Country) values ('Longtang', 'China');
insert into E_Place (City, Country) values ('Ivano-Frankove', 'Ukraine');
insert into E_Place (City, Country) values ('Ōzu', 'Japan');
insert into E_Place (City, Country) values ('Tílisos', 'Greece');
insert into E_Place (City, Country) values ('Shestakovo', 'Russia');
insert into E_Place (City, Country) values ('Concepción Tutuapa', 'Guatemala');
insert into E_Place (City, Country) values ('Arani', 'Bolivia');
insert into E_Place (City, Country) values ('Mengxingzhuang', 'China');
insert into E_Place (City, Country) values ('Fajões', 'Portugal');
insert into E_Place (City, Country) values ('Sucha', 'Poland');
insert into E_Place (City, Country) values ('Ōnojō', 'Japan');
insert into E_Place (City, Country) values ('Ta’erqi', 'China');
insert into E_Place (City, Country) values ('Sergeyevka', 'Russia');
insert into E_Place (City, Country) values ('Matiguás', 'Nicaragua');
insert into E_Place (City, Country) values ('Shashemenē', 'Ethiopia');
insert into E_Place (City, Country) values ('Garanhuns', 'Brazil');
insert into E_Place (City, Country) values ('Puente Nacional', 'Colombia');
insert into E_Place (City, Country) values ('Jiangjiazui', 'China');
insert into E_Place (City, Country) values ('Bobo-Dioulasso', 'Burkina Faso');
insert into E_Place (City, Country) values ('Sumurgung', 'Indonesia');
insert into E_Place (City, Country) values ('Shimo-furano', 'Japan');
insert into E_Place (City, Country) values ('Breda', 'Netherlands');
insert into E_Place (City, Country) values ('Fastovetskaya', 'Russia');
insert into E_Place (City, Country) values ('Goght’', 'Armenia');
insert into E_Place (City, Country) values ('Nakło nad Notecią', 'Poland');
insert into E_Place (City, Country) values ('Póvoa de Penela', 'Portugal');
insert into E_Place (City, Country) values ('Tyresö', 'Sweden');
insert into E_Place (City, Country) values ('Tagnanan', 'Philippines');
insert into E_Place (City, Country) values ('Piúma', 'Brazil');
insert into E_Place (City, Country) values ('Miyoshi', 'Japan');
insert into E_Place (City, Country) values ('Ambato Boeny', 'Madagascar');
insert into E_Place (City, Country) values ('Tama', 'Argentina');
insert into E_Place (City, Country) values ('Al Lagowa', 'Sudan');
insert into E_Place (City, Country) values ('Macari', 'Peru');
insert into E_Place (City, Country) values ('Doghs', 'Armenia');
insert into E_Place (City, Country) values ('Mengxi', 'China');
insert into E_Place (City, Country) values ('Ban Na San', 'Thailand');
insert into E_Place (City, Country) values ('Cai Doi Vam', 'Vietnam');
insert into E_Place (City, Country) values ('Stockholm', 'Sweden');
insert into E_Place (City, Country) values ('Sampués', 'Colombia');
insert into E_Place (City, Country) values ('Krajansumbermujur', 'Indonesia');
insert into E_Place (City, Country) values ('Beloyarskiy', 'Russia');
insert into E_Place (City, Country) values ('Kalidung', 'Indonesia');
insert into E_Place (City, Country) values ('Fenkeng', 'China');
insert into E_Place (City, Country) values ('Krasyliv', 'Ukraine');
insert into E_Place (City, Country) values ('Luoshan', 'China');
insert into E_Place (City, Country) values ('Zakliczyn', 'Poland');
insert into E_Place (City, Country) values ('Gunungputri', 'Indonesia');
insert into E_Place (City, Country) values ('Pondokwungu', 'Indonesia');
insert into E_Place (City, Country) values ('Chengnan', 'China');
insert into E_Place (City, Country) values ('Shakhun’ya', 'Russia');
insert into E_Place (City, Country) values ('Kuršumlija', 'Serbia');
insert into E_Place (City, Country) values ('Kvasice', 'Czech Republic');
insert into E_Place (City, Country) values ('Fengshan', 'China');
insert into E_Place (City, Country) values ('Naples', 'United States');
insert into E_Place (City, Country) values ('Liangbing', 'China');
insert into E_Place (City, Country) values ('Zhangdiyingzi', 'China');
insert into E_Place (City, Country) values ('Sérvia', 'Greece');
insert into E_Place (City, Country) values ('Orlando', 'United States');
insert into E_Place (City, Country) values ('Shinan', 'China');
insert into E_Place (City, Country) values ('Metulla', 'Israel');
insert into E_Place (City, Country) values ('Genisséa', 'Greece');
insert into E_Place (City, Country) values ('Yujia’ao', 'China');
insert into E_Place (City, Country) values ('Ndélé', 'Central African Republic');
insert into E_Place (City, Country) values ('Chengjiao', 'China');
insert into E_Place (City, Country) values ('Froly', 'Russia');
insert into E_Place (City, Country) values ('Yartsevo', 'Russia');
insert into E_Place (City, Country) values ('Girijaya', 'Indonesia');
insert into E_Place (City, Country) values ('Tissa', 'Morocco');
insert into E_Place (City, Country) values ('Brejo da Madre de Deus', 'Brazil');
insert into E_Place (City, Country) values ('Riofrío', 'Colombia');
insert into E_Place (City, Country) values ('Huangzhuang', 'China');
insert into E_Place (City, Country) values ('Casal', 'Portugal');
insert into E_Place (City, Country) values ('Cẩm Phả', 'Vietnam');
insert into E_Place (City, Country) values ('Shibetsu', 'Japan');
insert into E_Place (City, Country) values ('Changyanbao', 'China');
insert into E_Place (City, Country) values ('Toluviejo', 'Colombia');
insert into E_Place (City, Country) values ('Cikuya', 'Indonesia');
insert into E_Place (City, Country) values ('Yamparáez', 'Bolivia');
insert into E_Place (City, Country) values ('Beishan', 'China');
insert into E_Place (City, Country) values ('Vërtop', 'Albania');
insert into E_Place (City, Country) values ('General Conesa', 'Argentina');
insert into E_Place (City, Country) values ('Dadong', 'China');
insert into E_Place (City, Country) values ('Chociwel', 'Poland');
insert into E_Place (City, Country) values ('Calgary', 'Canada');
insert into E_Place (City, Country) values ('Sangkalputung', 'Indonesia');
insert into E_Place (City, Country) values ('Xinmen', 'China');
insert into E_Place (City, Country) values ('Chepes', 'Argentina');
insert into E_Place (City, Country) values ('Selydove', 'Ukraine');
insert into E_Place (City, Country) values ('Pangao', 'Philippines');
insert into E_Place (City, Country) values ('Novaya Igirma', 'Russia');
insert into E_Place (City, Country) values ('Karangtengah', 'Indonesia');
insert into E_Place (City, Country) values ('Zīrakī', 'Afghanistan');
insert into E_Place (City, Country) values ('Qiaoshi', 'China');
insert into E_Place (City, Country) values ('Paços de Ferreira', 'Portugal');
insert into E_Place (City, Country) values ('Toufang', 'China');
insert into E_Place (City, Country) values ('Sattahip', 'Thailand');
insert into E_Place (City, Country) values ('Arnaía', 'Greece');
insert into E_Place (City, Country) values ('Sadek', 'Vietnam');
insert into E_Place (City, Country) values ('Horvati', 'Croatia');
insert into E_Place (City, Country) values ('Khotynets', 'Russia');
insert into E_Place (City, Country) values ('Thomassique', 'Haiti');
insert into E_Place (City, Country) values ('Beijie', 'China');
insert into E_Place (City, Country) values ('San Ignacio', 'Belize');
insert into E_Place (City, Country) values ('Villa Nueva', 'Guatemala');
insert into E_Place (City, Country) values ('Nytva', 'Russia');
insert into E_Place (City, Country) values ('Xinglong', 'China');
insert into E_Place (City, Country) values ('Velká Polom', 'Czech Republic');
insert into E_Place (City, Country) values ('Tarkwa', 'Ghana');
insert into E_Place (City, Country) values ('Volovets', 'Ukraine');
insert into E_Place (City, Country) values ('Sidokumpul', 'Indonesia');
insert into E_Place (City, Country) values ('Leran Kulon', 'Indonesia');
insert into E_Place (City, Country) values ('Lapuz', 'Philippines');
insert into E_Place (City, Country) values ('Cerro Azul', 'Argentina');
insert into E_Place (City, Country) values ('Malasiqui', 'Philippines');
insert into E_Place (City, Country) values ('Iroquois Falls', 'Canada');
insert into E_Place (City, Country) values ('Panenjoan', 'Indonesia');
insert into E_Place (City, Country) values ('Créteil', 'France');
insert into E_Place (City, Country) values ('São Fidélis', 'Brazil');
insert into E_Place (City, Country) values ('Växjö', 'Sweden');
insert into E_Place (City, Country) values ('Idritsa', 'Russia');
insert into E_Place (City, Country) values ('Nashville', 'United States');
insert into E_Place (City, Country) values ('Zvole', 'Czech Republic');
insert into E_Place (City, Country) values ('Bielawa', 'Poland');
insert into E_Place (City, Country) values ('Pameungpeuk', 'Indonesia');
insert into E_Place (City, Country) values ('Rzozów', 'Poland');
insert into E_Place (City, Country) values ('Sviblovo', 'Russia');
insert into E_Place (City, Country) values ('Shashemenē', 'Ethiopia');
insert into E_Place (City, Country) values ('Funan Chengguanzhen', 'China');
insert into E_Place (City, Country) values ('Taocun', 'China');
insert into E_Place (City, Country) values ('Dadong’ao', 'China');
insert into E_Place (City, Country) values ('Tianzishan', 'China');
insert into E_Place (City, Country) values ('Richmond', 'New Zealand');
insert into E_Place (City, Country) values ('Jinshan', 'China');
insert into E_Place (City, Country) values ('Barra de São Francisco', 'Brazil');
insert into E_Place (City, Country) values ('Taquara', 'Brazil');
insert into E_Place (City, Country) values ('Sevilla', 'Spain');
insert into E_Place (City, Country) values ('Taluncemara', 'Indonesia');
insert into E_Place (City, Country) values ('Boka', 'Serbia');
insert into E_Place (City, Country) values ('Telagasari', 'Indonesia');
insert into E_Place (City, Country) values ('Genova', 'Italy');
insert into E_Place (City, Country) values ('Masingbi', 'Sierra Leone');
insert into E_Place (City, Country) values ('Cincinnati', 'United States');
insert into E_Place (City, Country) values ('Gonzalo Pizarro', 'Ecuador');
insert into E_Place (City, Country) values ('Socos', 'Peru');
insert into E_Place (City, Country) values ('Reni', 'Ukraine');
insert into E_Place (City, Country) values ('Žrnovo', 'Croatia');
insert into E_Place (City, Country) values ('Kamennyye Potoki', 'Ukraine');
insert into E_Place (City, Country) values ('Pjanići', 'Bosnia and Herzegovina');
insert into E_Place (City, Country) values ('Buyant', 'Mongolia');
insert into E_Place (City, Country) values ('Jimenez', 'Philippines');
insert into E_Place (City, Country) values ('Priob’ye', 'Russia');
insert into E_Place (City, Country) values ('Fukuoka-shi', 'Japan');
insert into E_Place (City, Country) values ('Guanba', 'China');
insert into E_Place (City, Country) values ('Mashizhai', 'China');
insert into E_Place (City, Country) values ('Kedawung', 'Indonesia');
insert into E_Place (City, Country) values ('Morrinhos', 'Brazil');
insert into E_Place (City, Country) values ('Hoani', 'Comoros');
insert into E_Place (City, Country) values ('Krasnotur’insk', 'Russia');
insert into E_Place (City, Country) values ('Sīnah', 'Iraq');
insert into E_Place (City, Country) values ('Lelystad', 'Netherlands');
insert into E_Place (City, Country) values ('Martingança-Gare', 'Portugal');
insert into E_Place (City, Country) values ('Kotido', 'Uganda');
insert into E_Place (City, Country) values ('Jetafe', 'Philippines');
insert into E_Place (City, Country) values ('Irahuan', 'Philippines');
insert into E_Place (City, Country) values ('Chengqiao', 'China');
insert into E_Place (City, Country) values ('Ust’-Kut', 'Russia');
insert into E_Place (City, Country) values ('Inongo', 'Democratic Republic of the Congo');
insert into E_Place (City, Country) values ('Bordeaux', 'France');
insert into E_Place (City, Country) values ('Caetité', 'Brazil');
insert into E_Place (City, Country) values ('Tercena', 'Portugal');
insert into E_Place (City, Country) values ('Tallahassee', 'United States');
insert into E_Place (City, Country) values ('Āstārā', 'Iran');
insert into E_Place (City, Country) values ('Werota', 'Ethiopia');
insert into E_Place (City, Country) values ('Sharan', 'Russia');
insert into E_Place (City, Country) values ('Amirabad', 'Pakistan');
insert into E_Place (City, Country) values ('Lembanah', 'Indonesia');
insert into E_Place (City, Country) values ('Marhanets’', 'Ukraine');
insert into E_Place (City, Country) values ('Tomay Kichwa', 'Peru');
insert into E_Place (City, Country) values ('Sarvābād', 'Iran');
insert into E_Place (City, Country) values ('Banjar Serangan', 'Indonesia');
insert into E_Place (City, Country) values ('Bodzentyn', 'Poland');
insert into E_Place (City, Country) values ('Liugong', 'China');
insert into E_Place (City, Country) values ('Vespasiano', 'Brazil');
insert into E_Place (City, Country) values ('Adelaide Mail Centre', 'Australia');
insert into E_Place (City, Country) values ('Jilong', 'China');
insert into E_Place (City, Country) values ('Belsh', 'Albania');
insert into E_Place (City, Country) values ('Sawahbaru', 'Indonesia');
insert into E_Place (City, Country) values ('Kawangkoan', 'Indonesia');
insert into E_Place (City, Country) values ('Pandanrejokrajan', 'Indonesia');
insert into E_Place (City, Country) values ('Qukës-Skënderbe', 'Albania');
insert into E_Place (City, Country) values ('Pomar', 'Portugal');
insert into E_Place (City, Country) values ('Danidehe', 'Indonesia');
insert into E_Place (City, Country) values ('Xin’andu', 'China');
insert into E_Place (City, Country) values ('Montelíbano', 'Colombia');
insert into E_Place (City, Country) values ('Bukui', 'China');
insert into E_Place (City, Country) values ('Uuemõisa', 'Estonia');
insert into E_Place (City, Country) values ('Natonin', 'Philippines');
insert into E_Place (City, Country) values ('Chipinge', 'Zimbabwe');
insert into E_Place (City, Country) values ('Luchingu', 'Tanzania');
insert into E_Place (City, Country) values ('Yetang', 'China');
insert into E_Place (City, Country) values ('Eisen', 'South Korea');
insert into E_Place (City, Country) values ('Aulnay-sous-Bois', 'France');
insert into E_Place (City, Country) values ('Tazemmourt', 'Morocco');
insert into E_Place (City, Country) values ('Güines', 'Cuba');
insert into E_Place (City, Country) values ('Jiangyou', 'China');
insert into E_Place (City, Country) values ('Mathba', 'Bangladesh');
insert into E_Place (City, Country) values ('Mont-Tremblant', 'Canada');
insert into E_Place (City, Country) values ('Gorjani', 'Croatia');
insert into E_Place (City, Country) values ('Lazarat', 'Albania');
insert into E_Place (City, Country) values ('Getazat', 'Armenia');
insert into E_Place (City, Country) values ('Löddeköpinge', 'Sweden');
insert into E_Place (City, Country) values ('Shidu', 'China');
insert into E_Place (City, Country) values ('Paatan', 'Philippines');
insert into E_Place (City, Country) values ('Thomazeau', 'Haiti');
insert into E_Place (City, Country) values ('20 de Noviembre', 'Mexico');
insert into E_Place (City, Country) values ('Porto Calvo', 'Brazil');
insert into E_Place (City, Country) values ('Reshui', 'China');
insert into E_Place (City, Country) values ('Mionica', 'Bosnia and Herzegovina');
insert into E_Place (City, Country) values ('P’rimorsk’oe', 'Georgia');
insert into E_Place (City, Country) values ('Sergach', 'Russia');
insert into E_Place (City, Country) values ('San Agustin', 'Philippines');
insert into E_Place (City, Country) values ('‘Aşīrah ash Shamālīyah', 'Palestinian Territory');
insert into E_Place (City, Country) values ('Rudnya', 'Russia');
insert into E_Place (City, Country) values ('Chishtiān Mandi', 'Pakistan');
insert into E_Place (City, Country) values ('Sugcad', 'Philippines');
insert into E_Place (City, Country) values ('Camp Thorel', 'Mauritius');
insert into E_Place (City, Country) values ('Canillo', 'Andorra');
insert into E_Place (City, Country) values ('Oltintopkan', 'Tajikistan');
insert into E_Place (City, Country) values ('Ajung', 'Indonesia');
insert into E_Place (City, Country) values ('Fuyo', 'South Korea');
insert into E_Place (City, Country) values ('Tobias Barreto', 'Brazil');
insert into E_Place (City, Country) values ('Freiria', 'Portugal');
insert into E_Place (City, Country) values ('Gusev', 'Russia');
insert into E_Place (City, Country) values ('Vaulx-en-Velin', 'France');
insert into E_Place (City, Country) values ('Velas', 'Portugal');
insert into E_Place (City, Country) values ('Zhuting', 'China');
insert into E_Place (City, Country) values ('São Sebastião', 'Portugal');
insert into E_Place (City, Country) values ('Campina Grande', 'Brazil');
insert into E_Place (City, Country) values ('Jasper Park Lodge', 'Canada');
insert into E_Place (City, Country) values ('Xicheng', 'China');
insert into E_Place (City, Country) values ('Laya', 'Philippines');
insert into E_Place (City, Country) values ('Xincheng', 'China');
insert into E_Place (City, Country) values ('Erími', 'Cyprus');
insert into E_Place (City, Country) values ('Badean', 'Indonesia');
insert into E_Place (City, Country) values ('Intendente Alvear', 'Argentina');
insert into E_Place (City, Country) values ('Ferraria', 'Portugal');
insert into E_Place (City, Country) values ('Tbilisskaya', 'Russia');
insert into E_Place (City, Country) values ('Palmitas', 'Uruguay');
insert into E_Place (City, Country) values ('Bielawa', 'Poland');
insert into E_Place (City, Country) values ('Rabat', 'Morocco');
insert into E_Place (City, Country) values ('Masalovka', 'Russia');
insert into E_Place (City, Country) values ('Colombes', 'France');
insert into E_Place (City, Country) values ('Huamachuco', 'Peru');
insert into E_Place (City, Country) values ('Vnorovy', 'Czech Republic');
insert into E_Place (City, Country) values ('Fudian', 'China');
insert into E_Place (City, Country) values ('Gostovići', 'Bosnia and Herzegovina');
insert into E_Place (City, Country) values ('Bantry', 'Ireland');
insert into E_Place (City, Country) values ('Lijiapu', 'China');
insert into E_Place (City, Country) values ('Kuala Lumpur', 'Malaysia');
insert into E_Place (City, Country) values ('Kafr al Labad', 'Palestinian Territory');
insert into E_Place (City, Country) values ('Ūdalah', 'Palestinian Territory');
insert into E_Place (City, Country) values ('Alcorriol', 'Portugal');
insert into E_Place (City, Country) values ('Mariana', 'Brazil');
insert into E_Place (City, Country) values ('Hantsport', 'Canada');
insert into E_Place (City, Country) values ('Těšany', 'Czech Republic');
insert into E_Place (City, Country) values ('Upi', 'Philippines');
insert into E_Place (City, Country) values ('Malaba', 'Kenya');
insert into E_Place (City, Country) values ('La Ceja', 'Colombia');
insert into E_Place (City, Country) values ('Mayfa‘ah', 'Yemen');
insert into E_Place (City, Country) values ('Cennan', 'China');
insert into E_Place (City, Country) values ('Dayou', 'China');
insert into E_Place (City, Country) values ('Gharavŭtí', 'Tajikistan');
insert into E_Place (City, Country) values ('Lom Kao', 'Thailand');
insert into E_Place (City, Country) values ('Escuintla', 'Guatemala');
insert into E_Place (City, Country) values ('Mojokerto', 'Indonesia');
insert into E_Place (City, Country) values ('Pakkat', 'Indonesia');
insert into E_Place (City, Country) values ('Yinji', 'China');
insert into E_Place (City, Country) values ('Khairpur Nathan Shāh', 'Pakistan');
insert into E_Place (City, Country) values ('Yimamu', 'China');
insert into E_Place (City, Country) values ('Les Sables-d''Olonne', 'France');
insert into E_Place (City, Country) values ('Zuocun', 'China');
insert into E_Place (City, Country) values ('Plaju', 'Indonesia');
insert into E_Place (City, Country) values ('Pesagen', 'Indonesia');
insert into E_Place (City, Country) values ('Guazacapán', 'Guatemala');
insert into E_Place (City, Country) values ('Jose Maria Morelos', 'Mexico');
insert into E_Place (City, Country) values ('Birmingham', 'United States');
insert into E_Place (City, Country) values ('Angers', 'France');
insert into E_Place (City, Country) values ('Nanyanchuan', 'China');
insert into E_Place (City, Country) values ('Wufu', 'China');
insert into E_Place (City, Country) values ('Monastyryshche', 'Ukraine');
insert into E_Place (City, Country) values ('Wola Jachowa', 'Poland');
insert into E_Place (City, Country) values ('Tapiramutá', 'Brazil');
insert into E_Place (City, Country) values ('Buenos Aires', 'Peru');
insert into E_Place (City, Country) values ('Zhoutie', 'China');
insert into E_Place (City, Country) values ('Regla', 'Cuba');
insert into E_Place (City, Country) values ('Resistencia', 'Argentina');
insert into E_Place (City, Country) values ('Palumbungan', 'Indonesia');
insert into E_Place (City, Country) values ('Yŏnggwang-ŭp', 'North Korea');
insert into E_Place (City, Country) values ('Žirovnice', 'Czech Republic');
insert into E_Place (City, Country) values ('Montenegro', 'Colombia');
insert into E_Place (City, Country) values ('Wongka', 'Indonesia');
insert into E_Place (City, Country) values ('Pinghu', 'China');
insert into E_Place (City, Country) values ('Palma De Mallorca', 'Spain');
insert into E_Place (City, Country) values ('Kaberamaido', 'Uganda');
insert into E_Place (City, Country) values ('Saint-Pierre-Montlimart', 'France');
insert into E_Place (City, Country) values ('Chãos', 'Portugal');
insert into E_Place (City, Country) values ('Beidou', 'China');
insert into E_Place (City, Country) values ('Ciudad Cortés', 'Costa Rica');
insert into E_Place (City, Country) values ('Atimonan', 'Philippines');
insert into E_Place (City, Country) values ('Netanya', 'Israel');
insert into E_Place (City, Country) values ('Orange', 'France');
insert into E_Place (City, Country) values ('Yezhi', 'China');
insert into E_Place (City, Country) values ('Al ‘Awjah', 'Iraq');
insert into E_Place (City, Country) values ('Gromnik', 'Poland');
insert into E_Place (City, Country) values ('Wieniawa', 'Poland');
insert into E_Place (City, Country) values ('Jiangkou', 'China');
insert into E_Place (City, Country) values ('Santa Cecília', 'Brazil');
insert into E_Place (City, Country) values ('Sarapul', 'Russia');
insert into E_Place (City, Country) values ('Canavieiras', 'Brazil');
insert into E_Place (City, Country) values ('Demuk', 'Indonesia');
insert into E_Place (City, Country) values ('Gading', 'Indonesia');
insert into E_Place (City, Country) values ('Milówka', 'Poland');
insert into E_Place (City, Country) values ('Boyu', 'China');
insert into E_Place (City, Country) values ('San Agustín de Valle Fértil', 'Argentina');
insert into E_Place (City, Country) values ('San Luis', 'Argentina');
insert into E_Place (City, Country) values ('Sibayo', 'Peru');
insert into E_Place (City, Country) values ('Kimovsk', 'Russia');
insert into E_Place (City, Country) values ('Cuozhou', 'China');
insert into E_Place (City, Country) values ('Minas', 'Cuba');
insert into E_Place (City, Country) values ('Molde', 'Norway');
insert into E_Place (City, Country) values ('Muroto-misakicho', 'Japan');
insert into E_Place (City, Country) values ('Kuzhuping', 'China');
insert into E_Place (City, Country) values ('Padre Nabeto', 'Portugal');
insert into E_Place (City, Country) values ('Enyerhyetykaw', 'Belarus');
insert into E_Place (City, Country) values ('Sokol', 'Russia');
insert into E_Place (City, Country) values ('Cangshi', 'China');
insert into E_Place (City, Country) values ('Redcliff', 'Zimbabwe');
insert into E_Place (City, Country) values ('Milaor', 'Philippines');
insert into E_Place (City, Country) values ('Starodub', 'Russia');
insert into E_Place (City, Country) values ('Coronel Vivida', 'Brazil');
insert into E_Place (City, Country) values ('Cicurug', 'Indonesia');
insert into E_Place (City, Country) values ('Paragominas', 'Brazil');
insert into E_Place (City, Country) values ('Thị Trấn Mường Lát', 'Vietnam');
insert into E_Place (City, Country) values ('Ārifwāla', 'Pakistan');
insert into E_Place (City, Country) values ('Cinangka', 'Indonesia');
insert into E_Place (City, Country) values ('Souto', 'Portugal');
insert into E_Place (City, Country) values ('Fratar', 'Albania');
insert into E_Place (City, Country) values ('Little Current', 'Canada');
insert into E_Place (City, Country) values ('Stamford', 'United States');
insert into E_Place (City, Country) values ('Sjöbo', 'Sweden');
insert into E_Place (City, Country) values ('Krajan', 'Indonesia');
insert into E_Place (City, Country) values ('Floda', 'Sweden');
insert into E_Place (City, Country) values ('Erfangping', 'China');
insert into E_Place (City, Country) values ('Babica', 'Poland');
insert into E_Place (City, Country) values ('Daduo', 'China');
insert into E_Place (City, Country) values ('Indianapolis', 'United States');
insert into E_Place (City, Country) values ('Dabola', 'Guinea');
insert into E_Place (City, Country) values ('Birobidzhan', 'Russia');
insert into E_Place (City, Country) values ('Taltal', 'Chile');
insert into E_Place (City, Country) values ('Inda Silasē', 'Ethiopia');
insert into E_Place (City, Country) values ('Lumijoki', 'Finland');
insert into E_Place (City, Country) values ('Shenwan', 'China');
insert into E_Place (City, Country) values ('Juntang', 'China');
insert into E_Place (City, Country) values ('Shalya', 'Russia');
insert into E_Place (City, Country) values ('Bang Racham', 'Thailand');
insert into E_Place (City, Country) values ('Covão', 'Portugal');
insert into E_Place (City, Country) values ('Wenquan', 'China');
insert into E_Place (City, Country) values ('Ad Dawādimī', 'Saudi Arabia');
insert into E_Place (City, Country) values ('General Viamonte', 'Argentina');
insert into E_Place (City, Country) values ('Lama', 'Portugal');
insert into E_Place (City, Country) values ('Svojat', 'Bosnia and Herzegovina');
insert into E_Place (City, Country) values ('Tanahmerah', 'Indonesia');
insert into E_Place (City, Country) values ('Chişinău', 'Moldova');
insert into E_Place (City, Country) values ('Jam', 'Iran');
insert into E_Place (City, Country) values ('Lingquan', 'China');
insert into E_Place (City, Country) values ('Gubin', 'Poland');
insert into E_Place (City, Country) values ('Polyarnyye Zori', 'Russia');
insert into E_Place (City, Country) values ('Kotor', 'Montenegro');
insert into E_Place (City, Country) values ('Banjar Parekan', 'Indonesia');
insert into E_Place (City, Country) values ('Rosario', 'Philippines');
insert into E_Place (City, Country) values ('Umeå', 'Sweden');
insert into E_Place (City, Country) values ('Douz', 'Tunisia');
insert into E_Place (City, Country) values ('Guayabal', 'Colombia');
insert into E_Place (City, Country) values ('Talitsa', 'Russia');
insert into E_Place (City, Country) values ('Formosa do Rio Preto', 'Brazil');
insert into E_Place (City, Country) values ('Kumba', 'Cameroon');
insert into E_Place (City, Country) values ('La Sebala du Mornag', 'Tunisia');
insert into E_Place (City, Country) values ('Grijó', 'Portugal');
insert into E_Place (City, Country) values ('Mölndal', 'Sweden');
insert into E_Place (City, Country) values ('Zhelin', 'China');
insert into E_Place (City, Country) values ('Bradag', 'Indonesia');
insert into E_Place (City, Country) values ('Ngora', 'Uganda');
insert into E_Place (City, Country) values ('Rukem', 'Indonesia');
insert into E_Place (City, Country) values ('Thaba Nchu', 'South Africa');
insert into E_Place (City, Country) values ('San Benito', 'Philippines');
insert into E_Place (City, Country) values ('Panayagan', 'Indonesia');
insert into E_Place (City, Country) values ('Millerovo', 'Russia');
insert into E_Place (City, Country) values ('Jangkat', 'Indonesia');
insert into E_Place (City, Country) values ('Angered', 'Sweden');
insert into E_Place (City, Country) values ('Riachos', 'Portugal');
insert into E_Place (City, Country) values ('Wangfu', 'China');
insert into E_Place (City, Country) values ('Concordia', 'Argentina');
insert into E_Place (City, Country) values ('Zhvanets', 'Ukraine');
insert into E_Place (City, Country) values ('Nanjie', 'China');
insert into E_Place (City, Country) values ('Nevel’', 'Russia');
insert into E_Place (City, Country) values ('Shuangyang', 'China');
insert into E_Place (City, Country) values ('Fullerton', 'United States');
insert into E_Place (City, Country) values ('Rosario', 'Philippines');
insert into E_Place (City, Country) values ('Loufan', 'China');
insert into E_Place (City, Country) values ('Huayuan', 'China');
insert into E_Place (City, Country) values ('Hodošan', 'Croatia');
insert into E_Place (City, Country) values ('Huangyuan Chengguanzhen', 'China');
insert into E_Place (City, Country) values ('Wangge’ertang', 'China');
insert into E_Place (City, Country) values ('Datong', 'China');
insert into E_Place (City, Country) values ('Staryy Dobrotvir', 'Ukraine');
insert into E_Place (City, Country) values ('Longtian', 'China');
insert into E_Place (City, Country) values ('Buenavista', 'Philippines');
insert into E_Place (City, Country) values ('Zhaozhen', 'China');
insert into E_Place (City, Country) values ('Loen', 'Marshall Islands');
insert into E_Place (City, Country) values ('Lyakhovtsy', 'Ukraine');
insert into E_Place (City, Country) values ('Lubień', 'Poland');
insert into E_Place (City, Country) values ('Likupang', 'Indonesia');
insert into E_Place (City, Country) values ('Alor Setar', 'Malaysia');
insert into E_Place (City, Country) values ('Krajan Kerjo', 'Indonesia');
insert into E_Place (City, Country) values ('Gongjiang', 'China');
insert into E_Place (City, Country) values ('Pasarbaru', 'Indonesia');
insert into E_Place (City, Country) values ('Trảng Bom', 'Vietnam');
insert into E_Place (City, Country) values ('Paraiso', 'Philippines');
insert into E_Place (City, Country) values ('Lianokládhion', 'Greece');
insert into E_Place (City, Country) values ('Kommunar', 'Russia');
insert into E_Place (City, Country) values ('Goroka', 'Papua New Guinea');
insert into E_Place (City, Country) values ('Zhajin', 'China');
insert into E_Place (City, Country) values ('Tong’an', 'China');
insert into E_Place (City, Country) values ('Şabrātah', 'Libya');
insert into E_Place (City, Country) values ('Kedungringin', 'Indonesia');
insert into E_Place (City, Country) values ('Roi Et', 'Thailand');
insert into E_Place (City, Country) values ('Chitungwiza', 'Zimbabwe');
insert into E_Place (City, Country) values ('Joutseno', 'Finland');
insert into E_Place (City, Country) values ('Tbilisskaya', 'Russia');
insert into E_Place (City, Country) values ('Gahe', 'China');
insert into E_Place (City, Country) values ('Hengshan', 'China');
insert into E_Place (City, Country) values ('Cái Nhum', 'Vietnam');
insert into E_Place (City, Country) values ('Osvaldo Cruz', 'Brazil');
insert into E_Place (City, Country) values ('Isulan', 'Philippines');
insert into E_Place (City, Country) values ('Achada', 'Portugal');
insert into E_Place (City, Country) values ('Colombes', 'France');
insert into E_Place (City, Country) values ('Deranitan', 'Indonesia');
insert into E_Place (City, Country) values ('Guajiasi', 'China');
insert into E_Place (City, Country) values ('El Corozal', 'Honduras');
insert into E_Place (City, Country) values ('Cibeureum', 'Indonesia');
insert into E_Place (City, Country) values ('Wiang Chiang Rung', 'Thailand');
insert into E_Place (City, Country) values ('Norfolk', 'United States');
insert into E_Place (City, Country) values ('Kanḏay', 'Afghanistan');
insert into E_Place (City, Country) values ('Seixezelo', 'Portugal');
insert into E_Place (City, Country) values ('Shiojiri', 'Japan');
insert into E_Place (City, Country) values ('Suwaduk', 'Indonesia');
insert into E_Place (City, Country) values ('Alejal', 'Philippines');
insert into E_Place (City, Country) values ('Lodwar', 'Kenya');
insert into E_Place (City, Country) values ('Shouzhan', 'China');
insert into E_Place (City, Country) values ('Mariestad', 'Sweden');
insert into E_Place (City, Country) values ('Tembang', 'Indonesia');
insert into E_Place (City, Country) values ('Ribnica na Pohorju', 'Slovenia');
insert into E_Place (City, Country) values ('Chunhu', 'China');
insert into E_Place (City, Country) values ('Bagacay', 'Philippines');
insert into E_Place (City, Country) values ('Gouveia', 'Portugal');
insert into E_Place (City, Country) values ('Bálsamo Oriental', 'Honduras');
insert into E_Place (City, Country) values ('Koreiz', 'Ukraine');
insert into E_Place (City, Country) values ('Parobé', 'Brazil');
insert into E_Place (City, Country) values ('Shuangnian', 'China');
insert into E_Place (City, Country) values ('Kawagoe', 'Japan');
insert into E_Place (City, Country) values ('Bhadrapur', 'Nepal');
insert into E_Place (City, Country) values ('Eksjö', 'Sweden');
insert into E_Place (City, Country) values ('Huanglong', 'China');
insert into E_Place (City, Country) values ('Baturyn', 'Ukraine');
insert into E_Place (City, Country) values ('Sezemice', 'Czech Republic');
insert into E_Place (City, Country) values ('Kloulklubed', 'Palau');
insert into E_Place (City, Country) values ('Altkirch', 'France');
insert into E_Place (City, Country) values ('El Carmen', 'Argentina');
insert into E_Place (City, Country) values ('Dongmazar', 'China');
insert into E_Place (City, Country) values ('Melikkrajan', 'Indonesia');
insert into E_Place (City, Country) values ('Cincinnati', 'United States');
insert into E_Place (City, Country) values ('Novoishimskiy', 'Kazakhstan');
insert into E_Place (City, Country) values ('Gocoton', 'Philippines');
insert into E_Place (City, Country) values ('Anávra', 'Greece');
insert into E_Place (City, Country) values ('Bor', 'South Sudan');
insert into E_Place (City, Country) values ('Xinshao', 'China');
insert into E_Place (City, Country) values ('Sesheke', 'Zambia');
insert into E_Place (City, Country) values ('São Pedro', 'Portugal');
insert into E_Place (City, Country) values ('Матејче', 'Macedonia');
insert into E_Place (City, Country) values ('Ribeira', 'Portugal');
insert into E_Place (City, Country) values ('Mensalong', 'Indonesia');
insert into E_Place (City, Country) values ('Jarošov nad Nežárkou', 'Czech Republic');
insert into E_Place (City, Country) values ('Gaoping', 'China');
insert into E_Place (City, Country) values ('Lautaro', 'Chile');
insert into E_Place (City, Country) values ('Mannheim', 'Germany');
insert into E_Place (City, Country) values ('Dakingari', 'Nigeria');
insert into E_Place (City, Country) values ('Sovetskaya', 'Russia');
insert into E_Place (City, Country) values ('Krajenka', 'Poland');
insert into E_Place (City, Country) values ('Dalo', 'Indonesia');
insert into E_Place (City, Country) values ('Sampacho', 'Argentina');
insert into E_Place (City, Country) values ('Tobatí', 'Paraguay');
insert into E_Place (City, Country) values ('Pyatigorskiy', 'Russia');
insert into E_Place (City, Country) values ('Baruny', 'Belarus');
insert into E_Place (City, Country) values ('Serawai', 'Indonesia');
insert into E_Place (City, Country) values ('Danzi', 'China');
insert into E_Place (City, Country) values ('Shi’an', 'China');
insert into E_Place (City, Country) values ('Arhust', 'Mongolia');
insert into E_Place (City, Country) values ('Sumberrejo', 'Indonesia');
insert into E_Place (City, Country) values ('Xinshiba', 'China');
insert into E_Place (City, Country) values ('Ejmiatsin', 'Armenia');
insert into E_Place (City, Country) values ('Iwanuma', 'Japan');
insert into E_Place (City, Country) values ('Slovenska Bistrica', 'Slovenia');
insert into E_Place (City, Country) values ('Zuocun', 'China');
insert into E_Place (City, Country) values ('Moravský Písek', 'Czech Republic');
insert into E_Place (City, Country) values ('San Eduardo', 'Philippines');
insert into E_Place (City, Country) values ('Manicahan', 'Philippines');
insert into E_Place (City, Country) values ('Szamotuły', 'Poland');
insert into E_Place (City, Country) values ('Allealle', 'Indonesia');
insert into E_Place (City, Country) values ('Maguling', 'Philippines');
insert into E_Place (City, Country) values ('Sarany', 'Russia');
insert into E_Place (City, Country) values ('Jiantang', 'China');
insert into E_Place (City, Country) values ('Fika', 'Nigeria');
insert into E_Place (City, Country) values ('Tuchomie', 'Poland');
insert into E_Place (City, Country) values ('Moyuan', 'China');
insert into E_Place (City, Country) values ('Minggang', 'China');
insert into E_Place (City, Country) values ('Pliska', 'Bulgaria');
insert into E_Place (City, Country) values ('Quy Đạt', 'Vietnam');
insert into E_Place (City, Country) values ('Saraqinishtë', 'Albania');
insert into E_Place (City, Country) values ('Yuntan', 'China');
insert into E_Place (City, Country) values ('Sainte-Agathe-des-Monts', 'Canada');
insert into E_Place (City, Country) values ('Psary', 'Poland');
insert into E_Place (City, Country) values ('Rada Tilly', 'Argentina');
insert into E_Place (City, Country) values ('Szeged', 'Hungary');
insert into E_Place (City, Country) values ('Stockholm', 'Sweden');
insert into E_Place (City, Country) values ('Shetan', 'China');
insert into E_Place (City, Country) values ('Cerklje na Gorenjskem', 'Slovenia');
insert into E_Place (City, Country) values ('Lancaster', 'United States');
insert into E_Place (City, Country) values ('Khlong Khuean', 'Thailand');
insert into E_Place (City, Country) values ('Sarakhs', 'Iran');
insert into E_Place (City, Country) values ('Chimboy Shahri', 'Uzbekistan');
insert into E_Place (City, Country) values ('Melbourne', 'United States');
insert into E_Place (City, Country) values ('Caminaca', 'Peru');
insert into E_Place (City, Country) values ('Piotrków Kujawski', 'Poland');
insert into E_Place (City, Country) values ('León', 'Nicaragua');
insert into E_Place (City, Country) values ('Khokhryaki', 'Russia');
insert into E_Place (City, Country) values ('Bellavista', 'Peru');
insert into E_Place (City, Country) values ('Keffin Hausa', 'Nigeria');
insert into E_Place (City, Country) values ('Osveya', 'Belarus');
insert into E_Place (City, Country) values ('Bologna', 'Italy');
insert into E_Place (City, Country) values ('Dąbie', 'Poland');
insert into E_Place (City, Country) values ('Xiaoyi', 'China');
insert into E_Place (City, Country) values ('Puerto Francisco de Orellana', 'Ecuador');
insert into E_Place (City, Country) values ('Roanoke', 'United States');
insert into E_Place (City, Country) values ('Songhae', 'South Korea');
insert into E_Place (City, Country) values ('Liuzhi', 'China');
insert into E_Place (City, Country) values ('Moriya', 'Japan');
insert into E_Place (City, Country) values ('Da’an', 'China');
insert into E_Place (City, Country) values ('Oslo', 'Norway');
insert into E_Place (City, Country) values ('Jaša Tomić', 'Serbia');
insert into E_Place (City, Country) values ('Saguday', 'Philippines');
insert into E_Place (City, Country) values ('Sumalig', 'Philippines');
insert into E_Place (City, Country) values ('Tuba', 'China');
insert into E_Place (City, Country) values ('Sigou', 'China');
insert into E_Place (City, Country) values ('Ganjur', 'Indonesia');
insert into E_Place (City, Country) values ('Fanzeres', 'Portugal');
insert into E_Place (City, Country) values ('Pingtang', 'China');
insert into E_Place (City, Country) values ('Soacha', 'Colombia');
insert into E_Place (City, Country) values ('Chicago', 'United States');
insert into E_Place (City, Country) values ('St. Anton an der Jeßnitz', 'Austria');
insert into E_Place (City, Country) values ('Trelleborg', 'Sweden');
insert into E_Place (City, Country) values ('Sidokumpul', 'Indonesia');
insert into E_Place (City, Country) values ('Divinópolis', 'Brazil');
insert into E_Place (City, Country) values ('Tsybulevka', 'Ukraine');
insert into E_Place (City, Country) values ('Tiantai Chengguanzhen', 'China');
insert into E_Place (City, Country) values ('Ramaram', 'Indonesia');
insert into E_Place (City, Country) values ('Mhlambanyatsi', 'Swaziland');
insert into E_Place (City, Country) values ('Kapyl’', 'Belarus');
insert into E_Place (City, Country) values ('Czechowice-Dziedzice', 'Poland');
insert into E_Place (City, Country) values ('Madalena do Mar', 'Portugal');
insert into E_Place (City, Country) values ('Suyang', 'China');
insert into E_Place (City, Country) values ('Yabrūd', 'Syria');
insert into E_Place (City, Country) values ('Gorbunki', 'Russia');
insert into E_Place (City, Country) values ('Wakaseko', 'Indonesia');
insert into E_Place (City, Country) values ('Cesvaine', 'Latvia');
insert into E_Place (City, Country) values ('Palca', 'Peru');
insert into E_Place (City, Country) values ('Lisiy Nos', 'Russia');
insert into E_Place (City, Country) values ('R S', 'India');
insert into E_Place (City, Country) values ('Huangcai', 'China');
insert into E_Place (City, Country) values ('Bohicon', 'Benin');
insert into E_Place (City, Country) values ('Vista Hermosa', 'Mexico');
insert into E_Place (City, Country) values ('Luci', 'China');
insert into E_Place (City, Country) values ('Magistral’nyy', 'Russia');
insert into E_Place (City, Country) values ('Xilian', 'China');
insert into E_Place (City, Country) values ('Liurenba', 'China');
insert into E_Place (City, Country) values ('Seremban', 'Malaysia');
insert into E_Place (City, Country) values ('Naranjo', 'Costa Rica');
insert into E_Place (City, Country) values ('Dongjia', 'China');
insert into E_Place (City, Country) values ('Bollstabruk', 'Sweden');
insert into E_Place (City, Country) values ('Vetlanda', 'Sweden');
insert into E_Place (City, Country) values ('Paris 13', 'France');
insert into E_Place (City, Country) values ('Yorii', 'Japan');
insert into E_Place (City, Country) values ('Kfar NaOranim', 'Israel');
insert into E_Place (City, Country) values ('Mboto', 'Indonesia');
insert into E_Place (City, Country) values ('Jiangkou', 'China');
insert into E_Place (City, Country) values ('Qiying', 'China');
insert into E_Place (City, Country) values ('Stockton', 'United States');
insert into E_Place (City, Country) values ('Degeberga', 'Sweden');
insert into E_Place (City, Country) values ('Piaski', 'Poland');
insert into E_Place (City, Country) values ('Shiwan', 'China');
insert into E_Place (City, Country) values ('Samaro', 'Pakistan');
insert into E_Place (City, Country) values ('Pitkyaranta', 'Russia');
insert into E_Place (City, Country) values ('Kouqian', 'China');
insert into E_Place (City, Country) values ('Gaotan', 'China');
insert into E_Place (City, Country) values ('Winnica', 'Poland');
insert into E_Place (City, Country) values ('Resplendor', 'Brazil');
insert into E_Place (City, Country) values ('Onsala', 'Sweden');
insert into E_Place (City, Country) values ('Whitwell', 'United Kingdom');
insert into E_Place (City, Country) values ('Eldoret', 'Kenya');
insert into E_Place (City, Country) values ('Agago', 'Uganda');
insert into E_Place (City, Country) values ('Pindamonhangaba', 'Brazil');
insert into E_Place (City, Country) values ('Tugusirna', 'Indonesia');
insert into E_Place (City, Country) values ('Casal Novo', 'Portugal');
insert into E_Place (City, Country) values ('Sollefteå', 'Sweden');
insert into E_Place (City, Country) values ('Arujá', 'Brazil');
insert into E_Place (City, Country) values ('Lukovë', 'Albania');
insert into E_Place (City, Country) values ('Osielec', 'Poland');
insert into E_Place (City, Country) values ('Gunungmenang', 'Indonesia');
insert into E_Place (City, Country) values ('Đắk Mil', 'Vietnam');
insert into E_Place (City, Country) values ('Diaoluoshan', 'China');
insert into E_Place (City, Country) values ('Bode Sadu', 'Nigeria');
insert into E_Place (City, Country) values ('Huangkeng', 'China');
insert into E_Place (City, Country) values ('Hefu', 'China');
insert into E_Place (City, Country) values ('Mandepa Barat', 'Indonesia');
insert into E_Place (City, Country) values ('Vallehermoso', 'Philippines');
insert into E_Place (City, Country) values ('Guadalupe', 'Mexico');
insert into E_Place (City, Country) values ('No Kunda', 'Gambia');
insert into E_Place (City, Country) values ('Obudu', 'Nigeria');
insert into E_Place (City, Country) values ('Gorobinci', 'Macedonia');
insert into E_Place (City, Country) values ('Protección', 'Honduras');
insert into E_Place (City, Country) values ('Jiangwan', 'China');
insert into E_Place (City, Country) values ('Katav-Ivanovsk', 'Russia');
insert into E_Place (City, Country) values ('Abade de Vermoim', 'Portugal');
insert into E_Place (City, Country) values ('Tiedonglu', 'China');
insert into E_Place (City, Country) values ('Xinmatou', 'China');
insert into E_Place (City, Country) values ('Jaworzynka', 'Poland');
insert into E_Place (City, Country) values ('Narva-Jõesuu', 'Estonia');
insert into E_Place (City, Country) values ('Haebaru', 'Japan');
insert into E_Place (City, Country) values ('Shangzhang', 'China');
insert into E_Place (City, Country) values ('Balete', 'Philippines');
insert into E_Place (City, Country) values ('Farafenni', 'Gambia');
insert into E_Place (City, Country) values ('Bo Kluea', 'Thailand');
insert into E_Place (City, Country) values ('Bogdanovich', 'Russia');
insert into E_Place (City, Country) values ('Ugac Sur', 'Philippines');
insert into E_Place (City, Country) values ('Xiamao', 'China');
insert into E_Place (City, Country) values ('Ongabelen', 'Indonesia');
insert into E_Place (City, Country) values ('Fort Worth', 'United States');
insert into E_Place (City, Country) values ('Touzao', 'China');
insert into E_Place (City, Country) values ('Fengsheng', 'China');
insert into E_Place (City, Country) values ('Suohe', 'China');
insert into E_Place (City, Country) values ('Nordeste', 'Portugal');
insert into E_Place (City, Country) values ('Huaiyuan Chengguanzhen', 'China');
insert into E_Place (City, Country) values ('Asheville', 'United States');
insert into E_Place (City, Country) values ('San Luis', 'Mexico');
insert into E_Place (City, Country) values ('Las Breñas', 'Argentina');
insert into E_Place (City, Country) values ('Ipoh', 'Malaysia');
insert into E_Place (City, Country) values ('General Luna', 'Philippines');
insert into E_Place (City, Country) values ('Untolovo', 'Russia');
insert into E_Place (City, Country) values ('Limonade', 'Haiti');
insert into E_Place (City, Country) values ('Zhangcun', 'China');
insert into E_Place (City, Country) values ('Santana', 'Brazil');
insert into E_Place (City, Country) values ('Chita', 'Colombia');
insert into E_Place (City, Country) values ('Putrajaya', 'Malaysia');
insert into E_Place (City, Country) values ('Jiantang', 'China');
insert into E_Place (City, Country) values ('Bytkiv', 'Ukraine');
insert into E_Place (City, Country) values ('Jilib', 'Somalia');
insert into E_Place (City, Country) values ('Qārah', 'Syria');
insert into E_Place (City, Country) values ('Vinica', 'Croatia');
insert into E_Place (City, Country) values ('Sidomulyo', 'Indonesia');
insert into E_Place (City, Country) values ('Louisville', 'United States');
insert into E_Place (City, Country) values ('Tupã', 'Brazil');
insert into E_Place (City, Country) values ('Guyang', 'China');
insert into E_Place (City, Country) values ('Killorglin', 'Ireland');
insert into E_Place (City, Country) values ('Monte Mor', 'Brazil');
insert into E_Place (City, Country) values ('Kaset Wisai', 'Thailand');
insert into E_Place (City, Country) values ('Ipiales', 'Colombia');
insert into E_Place (City, Country) values ('Batobato', 'Philippines');
insert into E_Place (City, Country) values ('Beiwa', 'China');
insert into E_Place (City, Country) values ('Hai Riêng', 'Vietnam');
insert into E_Place (City, Country) values ('Xiangshan', 'China');
insert into E_Place (City, Country) values ('Cajazeiras', 'Brazil');
insert into E_Place (City, Country) values ('Sanhe', 'China');
insert into E_Place (City, Country) values ('Santa Catalina', 'Philippines');
insert into E_Place (City, Country) values ('Yongjiu', 'China');
insert into E_Place (City, Country) values ('Port-Cartier', 'Canada');
insert into E_Place (City, Country) values ('Pederneiras', 'Brazil');
insert into E_Place (City, Country) values ('Debre Werk’', 'Ethiopia');
